### ISSUE TITLE
digital envelope routines::unsupported

### ISSUE THREAD

**Issue by dustinlacewell** [shawwn/prompts-ai#1]
```
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/dustinlacewell/ext/gpt4/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/dustinlacewell/ext/gpt4/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/dustinlacewell/ext/gpt4/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/dustinlacewell/ext/gpt4/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/dustinlacewell/ext/gpt4/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/dustinlacewell/ext/gpt4/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/dustinlacewell/ext/gpt4/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/dustinlacewell/ext/gpt4/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/Users/dustinlacewell/ext/gpt4/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/dustinlacewell/ext/gpt4/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/dustinlacewell/ext/gpt4/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/dustinlacewell/ext/gpt4/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/dustinlacewell/ext/gpt4/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/dustinlacewell/ext/gpt4/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/dustinlacewell/ext/gpt4/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/dustinlacewell/ext/gpt4/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/dustinlacewell/ext/gpt4/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

OSX 12.6

**Comment by dustinlacewell** [comment]
This can be fixed by downgrading node or telling it to use the legacy openssl provider.

https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported
